spring:
  application:
    name: user
  profiles:
    active: dev
  datasource:
    schema: classpath:db/schema-h2.sql
    data: classpath:db/data-h2.sql

server:
  # listen port for incoming HTTP requests
  port: 8765

eureka:
  instance:
    # Use its IP Address rather than its hostname to registers with eureka.
    preferIpAddress: true
  client:
    serviceUrl:
      # defaultZone: http://localhost:8761/eureka/
      defaultZone: http://eureka.didispace.com/eureka/